### ISSUE TITLE
Extrinsics and 4 second action sequences not showing much movement

### ISSUE THREAD

**Issue by alecda573** [fabbrimatteo/JTA-Dataset#11]
Can you please explain how the three dimensional coordinates for your dataset were generated and also share the extrinsic parameters of camera used?

I have extracted 5 second action sequences for a specific person from different video files, and the first issue to generate nice gifs the subjects need to be roto translated. Have the camera coordinates been normalized in any way. If you could shed any light on how this was generated I would be thankful.

**Comment by fabbrimatteo** [comment]
The 3D coords are in the [standard camera system](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html). Unfortunately, I don't have the extrinsic parameters anymore. 
For your gifts, check this out: https://github.com/fabbrimatteo/LoCO

**Comment by alecda573** [comment]
@fabbrimatteo thanks for responding. This is very cool work, would you mind pointing me to the script that converts from camera space to world coordinates (as this appears to be the space of the gif outputs as they are not rotated)?

**Comment by alecda573** [comment]
Also, do you have the world coordinates still saved somewhere that could be shared?

**Comment by fabbrimatteo** [comment]
We never use world space coordinates in the code I pointed to you, we use camera coordinate. In your visualization, just place the camera position at (0, 0, 0) or play with the azimuth and you should be fine. Have a look at my [code](https://github.com/fabbrimatteo/LoCO/blob/c8296d789027d927756ee0fd5a622927aedcc468/demo.py#L54). Maybe [here](https://drive.google.com/file/d/1X4UzPd49zDcKcLzWDn1cBLMvhvJjHphl/view?usp=sharing) you can find the old camera coordinate in world space.
