### ISSUE TITLE
Location of different spines

### ISSUE THREAD

**Issue by rajatongit** [fabbrimatteo/JTA-Dataset#12]
Hello, 

Thank you very much for taking the time to create this dataset and making it available to the community.

I have a doubt  regarding the different joints that are annotated in the dataset. As mentioned in your README page, the joint indices 11 until 15 denote annotations on the spine. I was not able to understand where exactly these joints are located and the motivation behind having so many spine annotations?

My guess is that so many spine annotations might be needed for representing the spine as seen from the front (stomach, etc.) or as seen from the rear view of a person (back, kidneys, etc.), but I am not too sure about this; and feel that this kind of information might be helpful for others too.

**Comment by fabbrimatteo** [comment]
The only motivation behind the spine joints is that GTA provides them so we simply decided to store them all. We know that some of them are redundant. Feel free to ignore them!

**Comment by rajatongit** [comment]
Okay, thank you for your answer. :) Closing the issue now!
