### ISSUE TITLE
Inaccurate 2d poses

### ISSUE THREAD

**Issue by andreaskoelsch** [fabbrimatteo/JTA-Dataset#13]
Sometimes, 2d pose annotations are off beyond tolerance. Here's an example of a far away person. Here's an example:
![](https://imgur.com/5V4tV6q.png)

Zoomed in version for the person on the left side far away:
![](https://imgur.com/AoxCFiD.png)

I wonder if the projection is a bit off here or what could be the problem?

**Comment by fabbrimatteo** [comment]
This is a known problem due to the lens distortion added by the videogame. Unfortunately, there is no solution. The only thing you can do is to record the dataset again with [this mod](https://it.gta5-mods.com/misc/no-chromatic-aberration-lens-distortion-1-41) installed.

**Comment by isarandi** [comment]
Setting the focal length from 1158 to 1167 works quite nicely for me to fix this discrepancy.
