### ISSUE TITLE
I want to get the data set please!

### ISSUE THREAD

**Issue by Ared521** [fabbrimatteo/JTA-Dataset#15]
Dear author, I want to get the data set by sending the email to you, but the email fails to be sent. May I ask what should I do? Can you give me your email address? I appreciate it.

**Comment by fabbrimatteo** [comment]
Hi. Please, follow [this](https://github.com/fabbrimatteo/JTA-Dataset/issues/3#issuecomment-437082916).

**Comment by Ared521** [comment]
> Hi. Please, follow [this](https://github.com/fabbrimatteo/JTA-Dataset/issues/3#issuecomment-437082916).

Ok, I have sent it. Thank you very much indeed. Wish you all the best.

**Comment by Ared521** [comment]
> Hi. Please, follow [this](https://github.com/fabbrimatteo/JTA-Dataset/issues/3#issuecomment-437082916).

Thank you!
