### ISSUE TITLE
Can I get the bounding box?

### ISSUE THREAD

**Issue by Min-Hyuk98** [fabbrimatteo/JTA-Dataset#16]
I need the bounding box of each person. But there is no bounding box.
Should I get my own bounding box using other models or key points?

And I have one more question.
you wrote like below in the readme

''WARNING: on 21 February 2019 we have changed the annotations, converting the 3D coordinates to the standard camera coordinate system. [Here](https://drive.google.com/open?id=1JZ5usEbosabcjj_YXT1Wr33NddNCDn3Z) you can download the new annotations separately.''

But the link doesn't work. Can I get the new 3D coordinates?

Thanks

**Comment by fabbrimatteo** [comment]
You can obtain bounding boxes by calculating the extremes of each pose. If you recover x_min, x_max, y_min and y_max you have a bounding box.

If you download the dataset it already contains the new annotations! No need to re-download them!

**Comment by Min-Hyuk98** [comment]
Thank you for the reply!
