### ISSUE TITLE
Mask ground truth?

### ISSUE THREAD

**Issue by ghost** [fabbrimatteo/JTA-Dataset#2]
Is it possible that the mask groundtruth will be provided someday?

**Comment by fabbrimatteo** [comment]
We would love to have segmentation masks, but it is not one of our priorities at the moment.

Mask groundtruth annotation requires external software, such as [RenderDoc](https://renderdoc.org) which allows you to track down the rendering of the game. See also this paper [Playing for Benchmarks](http://vladlen.info/papers/playing-for-benchmarks.pdf) for further information.

**Comment by XianyuFFF** [comment]
> Is it possible that the mask groundtruth will be provided someday?
Have you got the mask gt? 
Do you have any way to get the mask groundtruth?
thank you
@Yuyangaichifan
