### ISSUE TITLE
How can I get the JTA-Key?

### ISSUE THREAD

**Issue by FoolishMao** [fabbrimatteo/JTA-Dataset#3]
Thanks for your works! And how can I get the JTA-Key?

**Comment by fabbrimatteo** [comment]
To obtain the **`JTA-Key`** please send an email to [Ing. Matteo Fabbri](http://imagelab.ing.unimore.it/imagelab/person.asp?idpersona=99) (with object "JTA Dataset Download") stating:

- Your name, title and affilation
- Your intended use of the data
- The following statement:

    > With this email we declare that we will use the JTA Dataset for research and educational purposes only, since we are aware that commercial use is prohibited. We also undertake to purchase a copy of Grand Theft Auto V.

We will promptly reply with the **`JTA-Key`**.

**Comment by ys198918** [comment]
Can you please offer your specific email address? Cos I cant open this ["matteo_DOT_fabbri_AT_unimore_DOT_it"](matteo_DOT_fabbri_AT_unimore_DOT_it)

**Comment by ys198918** [comment]
Can you please offer your specific email address? Cos I cant open this matteo_DOT_fabbri_AT_unimore_DOT_it

**Comment by ys198918** [comment]
Can you please offer your specific email address? Cos I cant open this [matteo_DOT_fabbri_AT_unimore_DOT_it](matteo_DOT_fabbri_AT_unimore_DOT_it)

**Comment by ys198918** [comment]
Can you please offer your specific email address?Cos I cant open your email link in  [Ing. Matteo Fabbri](http://imagelab.ing.unimore.it/imagelab/person.asp?idpersona=99).Thanks a lot.

**Comment by fabbrimatteo** [comment]
My mail address is **matteo`_DOT_`fabbri`_AT_`unimore`_DOT_`it**. You have to replace **`_DOT_`** with an actual dot (`.`) and **`_AT_`** with an actual at (`@`). 

We concealed my e-mail address to prevent spam.
