### ISSUE TITLE
Camera Intrinsic Matrix

### ISSUE THREAD

**Issue by mkocabas** [fabbrimatteo/JTA-Dataset#4]
Hi @fabbrimatteo,

Thanks for the great work! I need camera intrinsic matrix for a project. Do you have that? Do you use the same camera to render all of the videos?

**Comment by fabbrimatteo** [comment]
Hi @mkocabas,

Sorry for the delay.

We used the same camera to render all the videos. The intrinsic parameters of the camera are:

<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{align*}&space;&f_x&space;=&space;f_y&space;=&space;\frac{H}{2}\cdot\cot{\bigg(\frac{FOV}{2}\bigg)}\\&space;&c_x&space;=&space;\frac{W}{2}\\&space;&c_y&space;=&space;\frac{H}{2}&space;\end{align}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{align*}&space;&f_x&space;=&space;f_y&space;=&space;\frac{H}{2}\cdot\cot{\bigg(\frac{FOV}{2}\bigg)}\\&space;&c_x&space;=&space;\frac{W}{2}\\&space;&c_y&space;=&space;\frac{H}{2}&space;\end{align}" title="\begin{align*} &f_x = f_y = \frac{H}{2}\cdot\cot{\bigg(\frac{FOV}{2}\bigg)}\\ &c_x = \frac{W}{2}\\ &c_y = \frac{H}{2} \end{align}" /></a>

Where *W* and *H* are the width and height of the 2D plane (in our case are 1920 and 1080). FOV is the vertical field of view that is always 50 degree (note that you have to convert the FOV in radiants)

This [issue](https://github.com/fabbrimatteo/JTA-Mods/issues/3) may help you.

**Comment by mkocabas** [comment]
Thanks for the clear reply @fabbrimatteo. It'd be better to share this info on the `README` page.
