### ISSUE TITLE
About the camera's extrinsic parameters

### ISSUE THREAD

**Issue by Rimay** [fabbrimatteo/JTA-Dataset#6]
Hello, thanks for your great work, and I am curious about the extrinsic parameters of the cameras, specifically I want to know the rotation and translation parameters of each sequence of the JTA datasets, and then I want to transform the 3d joints from world coordinate to camera coordinate, can you provide any help？
thanks :)

**Comment by fabbrimatteo** [comment]
The annotations already provide the 2D coordinates. [Here](https://github.com/fabbrimatteo/JTA-Dataset#camera) you can find the intrinsic parameters of the whole dataset. We do not provide extrinsic camera parameters since the 3D coordinates are already roto-translated.

**Comment by Rimay** [comment]
> The annotations already provide the 2D coordinates. [Here](https://github.com/fabbrimatteo/JTA-Dataset#camera) you can find the intrinsic parameters of the whole dataset. We do not provide extrinsic camera parameters since the 3D coordinates are already roto-translated.

do you mean the 3d coordinate in the annotation file is based on the camera's coordinate ？

**Comment by fabbrimatteo** [comment]
Yes, 3D coordinates are expressed in camera space.
