### ISSUE TITLE
Is there a away to convert all sequences as one whole dataset?

### ISSUE THREAD

**Issue by Vhunon** [fabbrimatteo/JTA-Dataset#7]
Hello,

first thank you for this amazing dataset.
However, I find it kind of troublesome to train the data sequencewise. Is there a trick where all images are stored in one `images` folder with the appropriate ID in one `annotation` file?

**Comment by fabbrimatteo** [comment]
Hi,
Thank you for using our dataset!
There is no real trick, I guess you can simply modify `to_imgs.py` and `to_poses.py` to fit your needs.

Keep in mind that having a single annotation file will cost you a huge amount of time to read it all. I suggest you to store only one every 10 frames.

**Comment by Vhunon** [comment]
Thank you, you are right!
Another question using your COCO conversion script, COCO has a total number of 17 keypoints, however your script provides up to 22. Is there a trick to get the 17 standardized kpts?

**Comment by fabbrimatteo** [comment]
Unfortunately there is no way because our keypoints are different: for example, we do not have eyes and ears. The COCO style annotations were thought out for people who already have code written for COCO.
