### ISSUE TITLE
[Solution] visualize.py errors: "** On entry to DGEBAL parameter number  3 had an illegal value" 

### ISSUE THREAD

**Issue by suhrmann** [fabbrimatteo/JTA-Dataset#8]
_**FYI** I just stumbled over it - Feel free to close this issue when numpy fixes this or if you find this issue trivial_

### Problem
Running ``visualize.py`` on Windows 10 errors with:
```
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
 . . .
RuntimeError: The current Numpy installation ('C:\\Users\\Simon\\.conda\\envs\\jta-dataset\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```
This is caused by (currently latest) ``numpy v1.19.4`` - more specific by underlying ``fmod()`` on Windows 2004 or later

### Solution
Suggested solution in [numpy/issues/17746](https://github.com/numpy/numpy/issues/17746#issuecomment-724782963) is to install ``numpy==1.19.3`` (e.g. via [requirements.txt#L4](https://github.com/fabbrimatteo/JTA-Dataset/blob/master/requirements.txt#L4) )

**Comment by fabbrimatteo** [comment]
Thank you very much for reporting this problem. I excluded that specific numpy version directly in the `requirements.txt`.

**Comment by suhrmann** [comment]
You excluded the wrong numpy version:
The error happens on ``numpy 1.19.4``, but your line ``numpy>=1.15,!=1.19.3`` excludes ``1.19.3``, right?
**Update:** Just varified it: It should be ``numpy>=1.15,!=1.19.4``

(Sorry for the broken link in to the numpy issue in OP - I fixed it now)

**Comment by fabbrimatteo** [comment]
Ops you are right! Fixed it.

**Comment by suhrmann** [comment]
Now it works. Thank you for the quick response!
