### ISSUE TITLE
[Solution] RuntimeError: imageio.ffmpeg.download() has been deprecated.

### ISSUE THREAD

**Issue by suhrmann** [fabbrimatteo/JTA-Dataset#9]
### Problem
When running ``visualize.py`` on Windows 10 I get the error
```
RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'
```
But ``imageio-ffmpeg`` requires code adjustments due to changed API.

### Solution 
As a workaround you can nail down ``imageio==2.4.1`` (as suggested by [superuser.com/a/1403025/417244](https://superuser.com/a/1403025/417244)).

**Comment by fabbrimatteo** [comment]
Thank you for pointing it out. We solved the issue by adding `imageio-ffmpeg` in the requirements and removing `imageio.plugins.ffmpeg.download()` in `visualize.py`.
